export const team = [
  {
    id: 1,
    name: "Ashwin Gaidhani",
    role: "CEO & Founder",
    image: "/images/team/member-1.jpg",
    linkedin: "https://linkedin.com/",
    slug: "ashwin-gaidhani",
  },
  {
    id: 2,
    name: "Yagnaseni Gaidhani",
    role: "CEO",
    image: "/images/team/member-2.jpg",
    linkedin: "https://linkedin.com/",
    slug: "yagnaseni-gaidhani",
  },
  {
    id: 3,
    name: "Ajas S",
    role: "Creative Director",
    image: "/images/team/member-3.jpg",
    linkedin: "https://linkedin.com/",
    slug: "ajas-s",
  },
  {
    id: 4,
    name: "Neeraj Bilolikar",
    role: "Head of Marketing",
    image: "/images/team/member-4.jpg",
    linkedin: "https://linkedin.com/",
    slug: "neeraj-bilolikar",
  },
  {
    id: 5,
    name: "Saurav Patra",
    role: "GTM Strategy",
    image: "/images/team/member-5.jpg",
    linkedin: "https://linkedin.com/",
    slug: "saurav-patra",
  },
  {
    id: 6,
    name: "Shreya Gir",
    role: "Project",
    image: "/images/team/member-6.jpg",
    linkedin: "https://linkedin.com/",
    slug: "shreya-gir",
  },
];